// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlAfbewXxJQQmVWLasH6T4zE5w3q_s_DQ',
    appId: '1:169974508974:web:620366f7d3900a1143ac3f',
    messagingSenderId: '169974508974',
    projectId: 'home-sewa-43c55',
    authDomain: 'home-sewa-43c55.firebaseapp.com',
    storageBucket: 'home-sewa-43c55.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgmSshgwgeibyjlaDFq3wFDkKforWXm1A',
    appId: '1:169974508974:android:312bcb2d7c97d10f43ac3f',
    messagingSenderId: '169974508974',
    projectId: 'home-sewa-43c55',
    storageBucket: 'home-sewa-43c55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW9-DljjjK-3NqbttaBjAUPtChpOT8bbk',
    appId: '1:169974508974:ios:5e057938fa29376f43ac3f',
    messagingSenderId: '169974508974',
    projectId: 'home-sewa-43c55',
    storageBucket: 'home-sewa-43c55.appspot.com',
    iosClientId: '169974508974-usd0rpgjtckpm5erlikt0n3ohk860if4.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeSewa',
  );
}
